name: Deploying to GH Pages 

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test -- --coverage --watchAll=false

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  BRANCH: gh-pages
                  FOLDER: build
